apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/name: cms-job-20210311094424
  name: cms-job-20210311094424
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - sh
        - -e
        - -c
        - 'echo "Loading settings $DJANGO_SETTINGS_MODULE"


          # Import demo course

          git clone https://github.com/edx/edx-demo-course --branch open-release/koa.2
          --depth 1 ../edx-demo-course

          python ./manage.py cms import ../data ../edx-demo-course


          # Re-index courses

          ./manage.py cms reindex_course --all --setup'
        env:
        - name: SERVICE_VARIANT
          value: cms
        image: docker.io/overhangio/openedx:11.2.3
        name: cms
        volumeMounts:
        - mountPath: /openedx/edx-platform/lms/envs/tutor/
          name: settings-lms
        - mountPath: /openedx/edx-platform/cms/envs/tutor/
          name: settings-cms
        - mountPath: /openedx/config
          name: config
      restartPolicy: Never
      volumes:
      - configMap:
          name: openedx-settings-lms
        name: settings-lms
      - configMap:
          name: openedx-settings-cms
        name: settings-cms
      - configMap:
          name: openedx-config
        name: config
  ttlSecondsAfterFinished: 3600